version: "{build}"

os: Visual Studio 2015

platform:
  - x64

configuration:
  - Debug
  - Release
  
environment:
  INTR_QTDIR: "C:\\Qt\\5.7\\msvc2015_64\\"
  INTR_GIT_TOKEN: 
    secure: 7D4rb81yGcTOgpizeKD1m3vlSDc7tU9SNQdW4/LVdHzou7gMaKK01esf7/v/3ccB

install:
  - cd ..
  - git clone https://$(INTR_GIT_TOKEN)@github.com/begla/Intrinsic_Dependencies.git
  - cd Intrinsic
  - cd scripts_win32
  - call ConfigAndBuildDependencies.bat
  - cd ..

build_script:
  - cd scripts_win32
  - call Config.bat
  - cd ../build
  - cmake --build . --config %CONFIGURATION%
