language: cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

compiler:
  - gcc
  
before_install:
# Clone private dependencies which are not part of the main repository
  - cd ..
  - git clone https://$INTR_GIT_TOKEN@github.com/begla/Intrinsic_Dependencies.git
  - cd Intrinsic

script:
  - cd scripts_linux
  - chmod +x Config_Release ConfigAndBuildDependencies Build
# Build dependencies
  - ./ConfigAndBuildDependencies
# Config via CMake
  - ./Config_Release
  - ./Build
  - cd ..
  
